general:
  commonVulnerabilities:
    - CVE-2003-1307
    - CVE-2007-0086
    - CVE-2019-3462
    - CVE-2003-1580
    - CVE-2007-1743
    - CVE-2011-3374
  bestPracticeVulnerabilities:
    - CIS-DI-0001
    - CIS-DI-0005
    - DKL-LI-0003
    - CIS-DI-0008
