apiVersion: v1
kind: Pod
metadata:
  name: croc-hunter
  labels:
    app: croc-hunter
spec:
  containers:
    - name: croc-hunter
      image: quay.io/lachie83/croc-hunter1
      ports:
        - containerPort: 8080
