name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@master
    - uses: azure/aks-set-context@users/shigupt/arc-test
      with:
        creds: '${{ secrets.AZURE_CREDS_ONPREM }}'
        resource-group: 'shiguptOnpremARC'
        cluster-name: 'onpremARCClus'
        aad-creds: '${{ secrets.AZURE_AADCREDS }}'
      
    - run: cat $KUBECONFIG
        
    - run: 'kubectl apply -f $GITHUB_WORKSPACE/deployment.yaml'
      
  
