name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@master
    - uses: azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_CREDS }}
        resource-group: 'shigupt-rg'
        cluster-name: 'shigupt'
    - uses: azure/k8s-deploy@v1
      with:
        manifests: manifest/**/*.yaml
        images: nginx:1.15 
