name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - run: echo env.AZURE_HTTP_USER_AGENT
    - uses: azure/login@v1
      with:
        creds: '${{ secrets.AZURE_CREDS }}'
    - uses: azure/policy-compliance-scan@v0
      with:
        scopes: |
            /subscriptions/c00d16c7-6c1f-4c03-9be1-6934a4c49682/resourcegroups/shigupt-rg/providers/Microsoft.ContainerService/managedClusters/sgtest1
