name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@master
    - uses: stigok/k8s-set-context@releases/v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }} 
    
    - run: 'kubectl apply -f $GITHUB_WORKSPACE/deployment.yaml'
