name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@master
    - uses: azure/k8s-set-context@cluster-connect
      with:
        cluster-type: 'arc'
        creds: ${{ secrets.AZURE_CREDS }}
        cluster-name: 'demo-arc-cluster'
        resource-group: 'demo-arc-rg'
        token: '${{ secrets.TOKEN }}'
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          deployment.yaml
