name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: shiguptacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    - run: docker images
