name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@master
    - uses: azure/k8s-set-context@users/shigupt/arc-set-context
      with:
        cluster-type: 'arc'
        creds: '${{ secrets.AZURE_CREDS }}'
        token: '${{ secrets.SA_TOKEN }}'
        resource-group: 'shigupt-rg-arc-nonaad'
        cluster-name: 'shigupt-clus-arc-nonaad'
      
    - run: cat $KUBECONFIG
        
    - run: 'kubectl apply -f $GITHUB_WORKSPACE/deployment.yaml'     
  
