name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
#       - uses: azure/login@v1
#         with:
#           creds: '${{ secrets.AZURE_CREDS_TEST }}' 
    - uses: actions/checkout@master
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDS_TEST }}'
        resource-group: 'shigupt'
        cluster-name: 'shigupt-clus'
    - uses: azure/k8s-bake@v1
      id: bake
      with:
        renderEngine: helm
        helmChart: './demo-chart'  
    - uses: azure/k8s-deploy@v1
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
    - run: kubectl get deploy  
          

