name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: azure/aks-set-context@users/shigupt/updating-set-env
      with:
        creds: '${{ secrets.AZURE_CREDS }}'
        resource-group: shigupt-rg
        cluster-name: shigupt  
#     - uses: azure/aks-set-context@users/shigupt/changeKubeconfigPerms
#       with:
#         creds: '${{ secrets.AZURE_CREDS }}'
#         resource-group: 'shigupt-rg'
#         cluster-name: 'shigupt'
#     - uses: azure/setup-helm@v1
#     - run: helm version --client --short
