name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
#       - uses: azure/login@v1
#         with:
#           creds: '${{ secrets.AZURE_CREDS_TEST }}' 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDS_TEST }}'
        resource-group: 'shigupt'
        cluster-name: 'shigupt-clus'
    - run: kubectl apply -f deployment.yaml 
          

