name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        
    - uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.DIVMAN_KUBE_CONFIG }}

    - uses: Azure/k8s-deploy@users/shigupt/addingKubectlDescribeOutputInLogs-testing
      name: Kubernetes deploy
      with:
        namespace: default
        manifests: |
          deployment.yaml
          service.yaml
          pod.yaml
        strategy: canary
        traffic-split-method: pod
        percentage: 60
