name: manage-azure-policy-fb34e7d8
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'test-2/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'test-2/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**'
#      - 'test-2/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'test-2/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**'
#      - 'test-2/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**'
#      - 'test-2/policies/SQL_Managed_Instance_TDE_protector_should_be_encrypted_with_your_own_key_048248b0-55cd-46da-b1ff-39efd52db260/**'
#      - 'test-2/policies/_Preview_:_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**'
#      - 'test-2/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**'
#      - 'test-2/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_(CMK)_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**'
#      - 'test-2/policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**'
#      - 'test-2/policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**'
#      - 'test-2/policies/Private_endpoint_should_be_enabled_for_PostgreSQL_servers_0564d078-92f5-4f97-8398-b9f58a51f70b/**'
#      - 'test-2/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**'
#      - 'test-2/policies/Diagnostic_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**'
#      - 'test-2/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**'
#      - 'test-2/policies/Public_network_access_should_be_disabled_for_Cognitive_Services_accounts_0725b4dd-7e76-479c-a735-68e7ee23d5ca/**'
#      - 'test-2/policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**'
#      - 'test-2/policies/Deploy_Log_Analytics_agent_for_Windows_VMs_0868462e-646c-4fe3-9ced-a733534b6a2c/**'
#      - 'test-2/policies/Audit_Windows_machines_on_which_the_DSC_configuration_is_not_compliant_08a2f2d2-94b2-4a7b-aa3b-bb3f523ee6fd/**'
#      - 'test-2/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**'
#      - 'test-2/initiatives/_Preview_:_NIST_SP_800-171_R2_03055927-78bd-4236-86c0-f36125a10dc9/**'
#      - 'test-2/initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**'
#      - 'test-2/initiatives/IRS1075_September_2016_105e0327-6175-4eb2-9af4-1fba43bdb39d/**'
#      - 'test-2/initiatives/_Preview_:_Deploy_prerequisites_to_enable_Guest_Configuration_policies_on_virtual_machines_12794019-7a00-42cf-95c2-882eed337cc8/**'
#      - 'test-2/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**'
#      - 'test-2/initiatives/Enable_Monitoring_in_Azure_Security_Center_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**'
#      - 'test-2/initiatives/UK_OFFICIAL_and_UK_NHS_3937f550-eedd-4639-9c5e-294358be442e/**'
#      - 'test-2/initiatives/_Preview_:_Australian_Government_ISM_PROTECTED_27272c0b-c225-4cc3-b8b0-f2534b093077/**'
#      - 'test-2/initiatives/_Preview_:_SWIFT_CSP-CSCF_v2020_3e0c67fc-8c7c-406c-89bd-6b6bdc986a22/**'
#      - 'test-2/initiatives/_Preview_:_Azure_Security_Benchmark_42a694ed-f65e-42b2-aa9e-8052e9740a92/**'
#      - 'test-2/initiatives/Kubernetes_cluster_pod_security_restricted_standards_for_Linux-based_workloads_42b8ef37-b724-4e24-bbc8-7a7708edfe00/**'
#      - 'test-2/initiatives/PCI_v3.2.1:2018_496eeda9-8f2f-4d5e-8dfd-204f0a92ed41/**'
#      - 'test-2/initiatives/Canada_Federal_PBMM_4c4a5f27-de81-430b-b4e5-9cbd50595a87/**'
#      - 'test-2/initiatives/Enable_Azure_Monitor_for_VMs_55f3eceb-5573-4f18-9695-226972c6d74a/**'
#      - 'test-2/initiatives/Enable_Azure_Monitor_for_Virtual_Machine_Scale_Sets_75714362-cae7-409e-9b99-a8e5075b7fad/**'
#      - 'test-2/initiatives/ISO_27001:2013_89c6cddc-1c73-4ac1-b19c-54d1a15a42f2/**'
#      - 'test-2/initiatives/_Preview_:_Motion_Picture_Association_of_America_(MPAA)_92646f03-e39d-47a9-9e24-58d60ef49af8/**'
#      - 'test-2/initiatives/_Preview_:_Enable_Data_Protection_Suite_9cb3cc7a-b39b-4b82-bc89-e5a5d9ff7b97/**'
#      - 'test-2/initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**'
#      - 'test-2/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**'
#      - .github/workflows/manage-azure-policy-fb34e7d8.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_fb34e7d8}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          test-2/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          test-2/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**
          test-2/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          test-2/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**
          test-2/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**
          test-2/policies/SQL_Managed_Instance_TDE_protector_should_be_encrypted_with_your_own_key_048248b0-55cd-46da-b1ff-39efd52db260/**
          test-2/policies/_Preview_:_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**
          test-2/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**
          test-2/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_(CMK)_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**
          test-2/policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**
          test-2/policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**
          test-2/policies/Private_endpoint_should_be_enabled_for_PostgreSQL_servers_0564d078-92f5-4f97-8398-b9f58a51f70b/**
          test-2/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**
          test-2/policies/Diagnostic_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**
          test-2/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**
          test-2/policies/Public_network_access_should_be_disabled_for_Cognitive_Services_accounts_0725b4dd-7e76-479c-a735-68e7ee23d5ca/**
          test-2/policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**
          test-2/policies/Deploy_Log_Analytics_agent_for_Windows_VMs_0868462e-646c-4fe3-9ced-a733534b6a2c/**
          test-2/policies/Audit_Windows_machines_on_which_the_DSC_configuration_is_not_compliant_08a2f2d2-94b2-4a7b-aa3b-bb3f523ee6fd/**
          test-2/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**
          test-2/initiatives/_Preview_:_NIST_SP_800-171_R2_03055927-78bd-4236-86c0-f36125a10dc9/**
          test-2/initiatives/Audit_machines_with_insecure_password_security_settings_095e4ed9-c835-4ab6-9439-b5644362a06c/**
          test-2/initiatives/IRS1075_September_2016_105e0327-6175-4eb2-9af4-1fba43bdb39d/**
          test-2/initiatives/_Preview_:_Deploy_prerequisites_to_enable_Guest_Configuration_policies_on_virtual_machines_12794019-7a00-42cf-95c2-882eed337cc8/**
          test-2/initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**
          test-2/initiatives/Enable_Monitoring_in_Azure_Security_Center_1f3afdf9-d0c9-4c3d-847f-89da613e70a8/**
          test-2/initiatives/UK_OFFICIAL_and_UK_NHS_3937f550-eedd-4639-9c5e-294358be442e/**
          test-2/initiatives/_Preview_:_Australian_Government_ISM_PROTECTED_27272c0b-c225-4cc3-b8b0-f2534b093077/**
          test-2/initiatives/_Preview_:_SWIFT_CSP-CSCF_v2020_3e0c67fc-8c7c-406c-89bd-6b6bdc986a22/**
          test-2/initiatives/_Preview_:_Azure_Security_Benchmark_42a694ed-f65e-42b2-aa9e-8052e9740a92/**
          test-2/initiatives/Kubernetes_cluster_pod_security_restricted_standards_for_Linux-based_workloads_42b8ef37-b724-4e24-bbc8-7a7708edfe00/**
          test-2/initiatives/PCI_v3.2.1:2018_496eeda9-8f2f-4d5e-8dfd-204f0a92ed41/**
          test-2/initiatives/Canada_Federal_PBMM_4c4a5f27-de81-430b-b4e5-9cbd50595a87/**
          test-2/initiatives/Enable_Azure_Monitor_for_VMs_55f3eceb-5573-4f18-9695-226972c6d74a/**
          test-2/initiatives/Enable_Azure_Monitor_for_Virtual_Machine_Scale_Sets_75714362-cae7-409e-9b99-a8e5075b7fad/**
          test-2/initiatives/ISO_27001:2013_89c6cddc-1c73-4ac1-b19c-54d1a15a42f2/**
          test-2/initiatives/_Preview_:_Motion_Picture_Association_of_America_(MPAA)_92646f03-e39d-47a9-9e24-58d60ef49af8/**
          test-2/initiatives/_Preview_:_Enable_Data_Protection_Suite_9cb3cc7a-b39b-4b82-bc89-e5a5d9ff7b97/**
          test-2/initiatives/HITRUST/HIPAA_a169a624-5599-4385-a696-c8d643089fab/**
          test-2/initiatives/Kubernetes_cluster_pod_security_baseline_standards_for_Linux-based_workloads_a8640138-9b0a-4a28-b8cb-1666c838647d/**
