name: manage-azure-policy-d471f556
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/_Preview_:_NIST_SP_800-171_R2_03055927-78bd-4236-86c0-f36125a10dc9/**'
#      - 'initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**'
#      - .github/workflows/manage-azure-policy-d471f556.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_d471f556}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/_Preview_:_NIST_SP_800-171_R2_03055927-78bd-4236-86c0-f36125a10dc9/**
          initiatives/CIS_Microsoft_Azure_Foundations_Benchmark_1.1.0_1a5bb27d-173f-493e-9568-eb56638dde4d/**
