name: manage-azure-policy-bf293d14
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'test-multithreading/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**'
#      - 'test-multithreading/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**'
#      - 'test-multithreading/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**'
#      - 'test-multithreading/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**'
#      - 'test-multithreading/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**'
#      - 'test-multithreading/policies/SQL_Managed_Instance_TDE_protector_should_be_encrypted_with_your_own_key_048248b0-55cd-46da-b1ff-39efd52db260/**'
#      - 'test-multithreading/policies/_Preview_:_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**'
#      - 'test-multithreading/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**'
#      - 'test-multithreading/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_(CMK)_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**'
#      - 'test-multithreading/policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**'
#      - 'test-multithreading/policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**'
#      - 'test-multithreading/policies/Private_endpoint_should_be_enabled_for_PostgreSQL_servers_0564d078-92f5-4f97-8398-b9f58a51f70b/**'
#      - 'test-multithreading/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**'
#      - 'test-multithreading/policies/Diagnostic_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**'
#      - 'test-multithreading/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**'
#      - 'test-multithreading/policies/Public_network_access_should_be_disabled_for_Cognitive_Services_accounts_0725b4dd-7e76-479c-a735-68e7ee23d5ca/**'
#      - 'test-multithreading/policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**'
#      - 'test-multithreading/policies/Deploy_Log_Analytics_agent_for_Windows_VMs_0868462e-646c-4fe3-9ced-a733534b6a2c/**'
#      - 'test-multithreading/policies/Audit_Windows_machines_on_which_the_DSC_configuration_is_not_compliant_08a2f2d2-94b2-4a7b-aa3b-bb3f523ee6fd/**'
#      - 'test-multithreading/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**'
#      - 'test-multithreading/policies/Adaptive_Network_Hardening_recommendations_should_be_applied_on_internet_facing_virtual_machines_08e6af2d-db70-460a-bfe9-d5bd474ba9d6/**'
#      - 'test-multithreading/policies/_Preview_:_Azure_Policy_Add-on_for_Kubernetes_service_(AKS)_should_be_installed_and_enabled_on_your_clusters_0a15ec92-a229-4763-bb14-0ea34a568f8d/**'
#      - 'test-multithreading/policies/Private_endpoint_should_be_enabled_for_MariaDB_servers_0a1302fb-a631-4106-9753-f3d494733990/**'
#      - 'test-multithreading/policies/Configure_backup_on_VMs_of_a_location_to_an_existing_central_Vault_in_the_same_location_09ce66bc-1220-4153-8104-e3f51c936913/**'
#      - 'test-multithreading/policies/Disk_encryption_should_be_applied_on_virtual_machines_0961003e-5a0a-4549-abde-af6a37f2724d/**'
#      - 'test-multithreading/policies/There_should_be_more_than_one_owner_assigned_to_your_subscription_09024ccc-0c5f-475e-9457-b7c0d9ed487b/**'
#      - .github/workflows/manage-azure-policy-bf293d14.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_bf293d14}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          test-multithreading/policies/Audit_virtual_machines_without_disaster_recovery_configured_0015ea4d-51ff-4ce3-8d8c-f3f8f0179a56/**
          test-multithreading/policies/Azure_Backup_should_be_enabled_for_Virtual_Machines_013e242c-8828-4970-87b3-ab247555486d/**
          test-multithreading/policies/Cognitive_Services_accounts_should_restrict_network_access_037eea7a-bd0a-46c5-9a66-03aea78705d3/**
          test-multithreading/policies/Audit_Linux_machines_that_have_the_specified_applications_installed_0447bc18-e2f7-4c0d-aa20-bff034275be1/**
          test-multithreading/policies/Azure_Cosmos_DB_allowed_locations_0473574d-2d43-4217-aefe-941fcdf7e684/**
          test-multithreading/policies/SQL_Managed_Instance_TDE_protector_should_be_encrypted_with_your_own_key_048248b0-55cd-46da-b1ff-39efd52db260/**
          test-multithreading/policies/_Preview_:_Network_traffic_data_collection_agent_should_be_installed_on_Linux_virtual_machines_04c4380f-3fae-46e8-96c9-30193528f602/**
          test-multithreading/policies/Deploy_Diagnostic_Settings_for_Service_Bus_to_Log_Analytics_workspace_04d53d87-841c-4f23-8a5b-21564380b55e/**
          test-multithreading/policies/Azure_API_for_FHIR_should_use_a_customer-managed_key_(CMK)_to_encrypt_data_at_rest_051cba44-2429-45b9-9649-46cec11c7119/**
          test-multithreading/policies/Deploy_Log_Analytics_agent_for_Linux_VMs_053d3325-282c-4e5c-b944-24faffd30d77/**
          test-multithreading/policies/Web_Application_Firewall_(WAF)_should_be_enabled_for_Azure_Front_Door_Service_055aa869-bc98-4af8-bafc-23f1ab6ffe2c/**
          test-multithreading/policies/Private_endpoint_should_be_enabled_for_PostgreSQL_servers_0564d078-92f5-4f97-8398-b9f58a51f70b/**
          test-multithreading/policies/Vulnerability_Assessment_settings_for_SQL_server_should_contain_an_email_address_to_receive_scan_reports_057d6cfe-9c4f-4a6d-bc60-14420ea1f1a9/**
          test-multithreading/policies/Diagnostic_logs_in_Azure_Data_Lake_Store_should_be_enabled_057ef27e-665e-4328-8ea3-04b3122bd9fb/**
          test-multithreading/policies/Audit_VMs_that_do_not_use_managed_disks_06a78e20-9358-41c9-923c-fb736d382a4d/**
          test-multithreading/policies/Public_network_access_should_be_disabled_for_Cognitive_Services_accounts_0725b4dd-7e76-479c-a735-68e7ee23d5ca/**
          test-multithreading/policies/CORS_should_not_allow_every_resource_to_access_your_Function_Apps_0820b7b9-23aa-4725-a1ce-ae4558f718e5/**
          test-multithreading/policies/Deploy_Log_Analytics_agent_for_Windows_VMs_0868462e-646c-4fe3-9ced-a733534b6a2c/**
          test-multithreading/policies/Audit_Windows_machines_on_which_the_DSC_configuration_is_not_compliant_08a2f2d2-94b2-4a7b-aa3b-bb3f523ee6fd/**
          test-multithreading/policies/Deploy_Diagnostic_Settings_for_Search_Services_to_Log_Analytics_workspace_08ba64b8-738f-4918-9686-730d2ed79c7d/**
          test-multithreading/policies/Adaptive_Network_Hardening_recommendations_should_be_applied_on_internet_facing_virtual_machines_08e6af2d-db70-460a-bfe9-d5bd474ba9d6/**
          test-multithreading/policies/_Preview_:_Azure_Policy_Add-on_for_Kubernetes_service_(AKS)_should_be_installed_and_enabled_on_your_clusters_0a15ec92-a229-4763-bb14-0ea34a568f8d/**
          test-multithreading/policies/Private_endpoint_should_be_enabled_for_MariaDB_servers_0a1302fb-a631-4106-9753-f3d494733990/**
          test-multithreading/policies/Configure_backup_on_VMs_of_a_location_to_an_existing_central_Vault_in_the_same_location_09ce66bc-1220-4153-8104-e3f51c936913/**
          test-multithreading/policies/Disk_encryption_should_be_applied_on_virtual_machines_0961003e-5a0a-4549-abde-af6a37f2724d/**
          test-multithreading/policies/There_should_be_more_than_one_owner_assigned_to_your_subscription_09024ccc-0c5f-475e-9457-b7c0d9ed487b/**
