on: 
  workflow_dispatch:

name: Provision azure resources
env:
  CLUSTER_NAME: ${{ acc.CLUSTER_NAME }}
  ACR_NAME: ${{ acc.ACR_NAME }}
  RESOURCE_GROUP_NAME: ${{ acc.RESOURCE_GROUP }}
  RESOURCE_GROUP_LOCATION: ${{ acc.RESOURCE_GROUP_LOCATION }}

jobs:
  provision-azure-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create resource group
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          if [ $(az group exists --name $RESOURCE_GROUP_NAME) = false ]; then
            az group create --name $RESOURCE_GROUP_NAME --location $RESOURCE_GROUP_LOCATION
          fi
    - name: Create AKS cluster
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          if [ $(az aks list -g $RESOURCE_GROUP_NAME --query "[?name=='$CLUSTER_NAME'].{NAME:name}") = [] ]; then
            az aks create -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --location $RESOURCE_GROUP_LOCATION --generate-ssh-keys
          fi
    - name: Create ACR
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          if [ $(az acr list -g $RESOURCE_GROUP_NAME --query "[?name=='$ACR_NAME'].{NAME:name}") = [] ]; then
            az acr create -g $RESOURCE_GROUP_NAME -n $ACR_NAME --location $RESOURCE_GROUP_LOCATION
          fi
          
