on: 
  workflow_dispatch:

name: Provision azure resources
env:
  RESOURCE_NAME: abcd
  RESOURCE_GROUP_NAME: shigupt-rg
  RESOURCE_GROUP_LOCATION: eastus

jobs:
  provision-azure-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Create resource group
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          if [ $(az group exists --name $RESOURCE_GROUP_NAME) = false ]; then
            az group create --name $RESOURCE_GROUP_NAME --location $RESOURCE_GROUP_LOCATION
          fi
    - name: Create AKS cluster
      uses: Azure/cli@1.0.4
      with:
        inlineScript: |
          if [ $(az aks list -g $RESOURCE_GROUP_NAME --query "[?name=='$RESOURCE_NAME'].{NAME:name}") = [] ]; then
            az aks create -g $RESOURCE_GROUP_NAME -n $RESOURCE_NAME --location $RESOURCE_GROUP_LOCATION
          fi
    
