on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: 'stable/cerebro'
      id: bake
