name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest   
    strategy: 
      matrix:
        node: ["0"]
                            
    steps:      
    - uses: actions/checkout@v1      
    - uses: azure/container-scan@v0
      name: Container scan
      with:
        image-name: shiguptacr.azurecr.io/demoimage
        add-CIS-checks: True 
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        severity-threshold: LOW  
        
    - uses: azure/container-scan@v0
      name: Container scan
      with:
        image-name: shiguptacr.azurecr.io/demoimage
        add-CIS-checks: True 
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
        severity-threshold: LOW  
#       env:
#         DOCKLE_AUTH_URL: https://registry.hub.docker.com
          
