name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v1      
    - uses: shigupt202/local-container-scan@users/shigupt/addingWhitelistHandler
      name: Container scan
      with:
        image-name: nginx
        add-CIS-checks: True 
        username: shivamg202
        password: ${{ secrets.PASSWORD }}
        severity-threshold: LOW                                      
          
