name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v1   
#     - name: Docker build
#       run: |
#         docker build -f ${{ github.workspace }}/Dockerfile -t testimage . 
    - uses: Azure/container-scan@releases/v0
      name: Container scan
      id: scan
#       continue-on-error: true
      with:
        image-name: nginx 
        username: shivamg202
        password: ${{ secrets.PASSWORD }}
        severity-threshold: LOW 
#         add-CIS-checks: true
    - name: Output
      run: cat ${{steps.scan.outputs.scan-report-path}}

