name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v1   
#     - name: Docker build
#       run: |
#         docker build -f ${{ github.workspace }}/Dockerfile -t testimage . 
    - uses: shigupt202/local-container-scan@releases/v1
      name: Container scan
      with:
#         image-name: testimage    
        image-name: shivamg202/phippy:test
        username: shivamg2020
        password: ${{ secrets.PASSWORD }}                        
          
