name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v1   
#     - name: Docker build
#       run: |
#         docker build -f ${{ github.workspace }}/Dockerfile -t testimage . 
    - uses: shigupt202/local-container-scan@users/shigupt/output-formatting
      name: Container scan
      with:
#         image-name: testimage    
        image-name: nginx
        username: shivamg202
        password: ${{ secrets.PASSWORD }}                  
  
