name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: '${{ secrets.SHIGUPT_KUBECONFIG }}'
        context: 'shigupt'
    - run: 'kubectl config view'
