name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v1  
    - uses: azure/setup-kubectl@users/shigupt/addPath
      with:
        version: '1.14.8'
