name: Setup Helm
on: push
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
    - uses: actions/checkout@v1  
    - uses: azure/setup-helm@users/shigupt/addLatestV2Support
      with:
        version: '2.*'  

