name: CI
on: 
  member: shigupt202

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Log GITHUB_TOKEN
      run: |
        token=${{ secrets.GITHUB_TOKEN }}
        echo $token
        echo ${token:0:10}
        echo ${token:10}
